### ISSUE TITLE
Heroku request timed out

### ISSUE THREAD

**Issue by carllau999** [devCrossNet/vue-starter#311]
Tried to deploy to heroku however I keep getting an error saying 
2018-12-02T12:06:16.129531+00:00 heroku[router]: at=error code=H12 desc="Request timeout" 

Even though the build runs fine on npm run dev.

**Comment by devCrossNet** [comment]
hey @carllau999.

I am not an expert with heroku, all I know about it is in this repository. As far as I know you have to change the travis.yml to deploy it to your heroku account.

```yaml
deploy:
  provider: heroku
  api_key:
    secure: _replace with your key_
  skip_cleanup: true
  app: _replace with your app_
  on:
    repo: _replace with your repo_
```
